apiVersion: v1
kind: Service
metadata:
  name: external-mysql-svc
  namespace : splitway-backend
spec:
  type: ClusterIP
  ports:
    - port: 3306          # MySQL 기본 포트
      targetPort: 3306    # Endpoint에서 정의한 포트와 일치
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-mysql-endpoints
  namespace : splitway-backend
subsets:
  - addresses:
      - ip: 138.2.123.128 # 외부 MySQL 서버의 IP 주소
    ports:
      - port: 3306        # MySQL 포트
