apiVersion: v1
kind: Service
metadata:
  name: splitway-proxy-service
  namespace: splitway-backend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: splitway-proxy
  type: LoadBalancer
