apiVersion: v1
kind: ConfigMap
metadata:
  name: splitway-proxy-config
  namespace: splitway-backend

data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
              proxy_pass             http://splitway-service:8080;
              proxy_set_header       Host $host;
        }

        location /stub_status {
            stub_status;
        }
      }
    }
