apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: splitway-prometheus
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:6.7.4
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_USERS_DEFAULT_THEME
              value: "light"

          volumeMounts:
            - name: config-datasources
              mountPath: "/etc/grafana/provisioning/datasources"
              readOnly: true

      volumes:
        - name: config-datasources
          configMap:
            name: grafana-config
            items:
              - key: datasource.yaml
                path: datasource.yaml
