apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: splitway-prometheus
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      basicAuth: false
      version: 1
      editable: true
