apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: splitway-monitoring
spec:
  selector:
    app: splitway-prometheus

  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
